#!/bin/zsh

#############################
# variables d'environnement #
#############################
#export MANPATH="/opt/local/share/man"


#export PATH="/opt/local/lib"
#export PATH="${PATH}:/opt/local/bin"
#export PATH="${PATH}:/usr/local/bin"
#export PATH="${PATH}:/usr/bin:/bin:"
#export PATH="${PATH}:/usr/sbin:/sbin"
#export PATH="${PATH}:/opt/X11/bin"
#export PATH="${PATH}:/Library/TeX/texbin"

export LANG="en_US.UTF-8"

####---------------------------------------------------####

DEFAULT_USER=mouginot
export WORK_PATH="/home/mouginot/work"
export APP_PATH="${WORK_PATH}/App"

export PATH="${HOME}/.local/bin:$PATH"
export WORK_PATH="/Users/mouginot/work"
export CYCLUS_PATH="${APP_PATH}/cyclus"

####---------------------------------------------------####

export kermit='kermit.ep.wisc.edu'
export ovh='vps204419.ovh.net'
export pi='10.130.35.96'
export git='git@github.com:Baaaaam/'




####---------------------------------------------------####
# Compilation

####---------------------------------------------------####


####---------------------------------------------------####
# MCNP

export MCNP_PATH=${APP_PATH}/MCNP

export PATH=$MCNP_PATH/MCNP_CODE/MCNP6/bin/:${PATH}
#export DATAPATH ="$MYHOME/base/MCNP_DATA"


####---------------------------------------------------####
# SERPENT
export SERPENT_PATH="${APP_PATH}/Serpent/"
export PATH=${PATH}:${SERPENT_PATH}

####---------------------------------------------------####
# root

export ROOTSYS=$APP_PATH/root
export PATH=${PATH}:${ROOTSYS}/bin
export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:/Users/mouginot/work/App/root/lib/"

####---------------------------------------------------####


####---------------------------------------------------####
# CLASS package libraries

export CLASS_PATH=${APP_PATH}/CLASS
export CLASS_include=${CLASS_PATH}/source/include
export CLASS_DB=${CLASS_PATH}/Database
export CLASS_lib=${CLASS_PATH}/lib
export PATH=${PATH}:${CLASS_PATH}/gui/bin

####---------------------------------------------------####










