#!/bin/zsh

source $HOME/.zsh_config/zsh/env_perso
source $HOME/.zsh_config/zsh/work

source $HOME/.zsh_config/zsh/macro
source $HOME/.zsh_config/zsh/alias

cd /usr/local/bin
source /usr/local/bin/thisroot.sh
cd




export PATH="/home/mouginot/.local/bin:${PATH}"
#export LD_LIBRARY_PATH="/home/mouginot/.local/lib/python3.6:${LD_LIBRARY_PATH}"



source $HOME/.zsh_config/zsh/ohmzsh

eval "$(thefuck --alias)"

# start a TMux session
export POWERLINE_CONFIG="/home/mouginot/.local/lib/python3.6/site-packages/powerline/bindings/tmux/powerline.conf"
export TERM=screen-256color
#
set -o shwordsplit
if [[ ! $TMUX ]]; then
    
    SESSIONS="PyNE Cyclus TechX DAGMC play main mini Uncertainty"

    function has-session {
      tmux has-session -t $1 2>/dev/null
    }
    
    function open_session
    {
      if [ "$?" -eq 1 ] ; then
        tmux new-session -d -s $1
      fi
    }

    #
    #MAIN 
    for x in $SESSIONS
    do
      has-session $x
      open_session $x
    done
fi
unset shwordsplit

#alias tmux="tmux source-file ~/.tmux.conf"
