#!/bin/zsh

source $HOME/.zsh_config/zsh/env_perso
source $HOME/.zsh_config/zsh/work

source $HOME/.zsh_config/zsh/macro
source $HOME/.zsh_config/zsh/alias

#export ROOTSYS=$APP_PATH/root-6.06.02/bld
#export PATH=${PATH}:${ROOTSYS}/bin
#export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:$ROOTSYS/lib/"
cd /usr/local/bin
source /usr/local/bin/thisroot.sh
cd


export PATH="/Users/mouginot/work/app/cyclus/pyne/bin:${PATH}"
export LD_LIBRARY_PATH="/Users/mouginot/work/app/cyclus/pyne/:${LD_LIBRARY_PATH}"


export PATH="/home/mouginot/.local/lib/bin:${PATH}"
export LD_LIBRARY_PATH="/home/mouginot/.local/lib/python2.7:${LD_LIBRARY_PATH}"



source $HOME/.zsh_config/zsh/ohmzsh

eval "$(thefuck --alias)"

# start a TMux session
function tmux_start
{
    if [[ ! $TMUX ]]; then
        export POWERLINE_CONFIG="/usr/local/lib/python2.7/dist-packages/powerline/bindings/tmux/powerline.conf"
        export TERM=screen-256color
        tmux  -u -2
    fi
}
alias tmux="tmux_start"
