#!/bin/zsh

alias py_switch="$HOME/.zsh_config/macros/py_switch"
#alias sed='gsed'
alias finder="open -a finder"

# MacOS alias
alias ql='quick-look'
alias ql='quick-look'

alias ssh='TERM=xterm-256color ssh'

alias vim='/opt/local/bin/vim'
alias vi='/opt/local/bin/vim'

# ENV Variable


export MANPATH="/opt/local/man:$MANPATH"
export MANPATH="/opt/local/share/man:$MANPATH"


export PATH="/opt/local/lib:/opt/local/bin:/opt/local/sbin:/opt/X11/bin:/Library/TeX/texbin:$PATH"


# Python 
export PY_VERSION="`python -c 'import sys; print(".".join(map(str, sys.version_info[:2])))'`"
export PATH="/Users/mouginot/Library/Python/${PY_VERSION}/bin:${PATH}"
export PATH="/opt/local/Library/Frameworks/Python.framework/Versions/${PY_VERSION}/bin:${PATH}"
export PYTHONPATH="$HOME/.local/lib/python${PY_VERSION}/site-packages"

# MOAB Environment Settings

export PYTHONPATH="${HOME}/work/app/DAGMC_bld/MOAB/lib/python${PY_VERSION}/site-packages:${PYTHONPATH}"



# CMake
export CMAKE_MODULE_PATH=/opt/local/include
export CMAKE_PREFIX_PATH=/opt/local

####---------------------------------------------------####
# HDF5

export HDF5_DIR=/opt/local/lib
export HDF5_ROOT=/opt/local/

export PATH="$PATH:${HDF5_DIR}"

####---------------------------------------------------####
export ROOTSYS="/opt/local/libexec/root6"

source $HOME/.zsh_config/zsh/env_perso
source $HOME/.zsh_config/zsh/work

source $HOME/.zsh_config/zsh/macro
source $HOME/.zsh_config/zsh/alias

plugins=(osx macports docker)

source $HOME/.zsh_config/zsh/ohmzsh
export POWERLINE_CONFIG="$HOME/Library/Python/${PY_VERSION}/lib/python/site-packages/powerline/bindings/tmux/powerline.conf"

# start a TMux session
#if [[ ! $TMUX ]]; then
#    export POWERLINE_CONFIG="/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/powerline/bindings/tmux/powerline.conf"
#    export TERM=screen-256color
#    
#    tmux -u #attach work || tmux -u new -s work
#    exit
#fi

eval "$(thefuck --alias)"
source $HOME/.zsh_config/zsh/_swc
