#!/bin/zsh
#
# Requires the e module (pip install e)
function =
{
  python -me `echo $@ | sed -e "s/x/*/g"`
}
alias calcul="="


function +
{
  python -me $@ 
}
alias plus="+"


function gitcd () 
{
  chdir $1;
  if [ -d ".git" ]; then
    git fetch --all -q
  fi
}


source cd_def
