#!/bin/zsh
#
function =
{
  python -me `echo $@ | sed -e "s/x/*/g"`
}
alias calcul="="


function +
{
  python -me $@ 
}
alias plus="+"


function gitcd () 
{
  chdir $1;
  if [ -d ".git" ]; then
    git fetch --all -q
  fi
}


function cyclus_release()
{
  export CYCLUS_DIR=$CYCLUS_PATH/cyclus
  export CYCAMORE_DIR=$CYCLUS_PATH/cycamore
  export CYMETRIC_DIR=$CYCLUS_PATH/cymetric
}

source cd_def
