#/bin/zsh
# Killer: share history between multiple shells
setopt SHARE_HISTORY
#
# # If I type cd and then cd again, only save the last one
setopt HIST_IGNORE_DUPS
#
# # Even if there are commands in between commands that are the same, still only save the last one
setopt HIST_IGNORE_ALL_DUPS


DEFAULT_USER=mouginot


#if [[ `hostname -s` =~ 'mouginotLaptop' || `hostname -s` =~ 'CoffeeBean' || `hostname` =~ 'engr.wisc.edu' || `hostname` =~ 'dhcp-v007-218' ]]; then
if [[ `hostname -s` =~ 'submit-3' ]]; then
  export COMP='HTC'
  source $HOME/.zsh_config/zsh/_chtc
elif [[ `hostname -s` =~ 'submit-4' ]]; then
  export COMP='HTC-4'
  source $HOME/.zsh_config/zsh/_chtc
elif [[ `hostname -s` =~ 'humblemenhir' ]]; then
  export COMP='menhir'
  source $HOME/.zsh_config/zsh/_kermit
elif [[ `hostname -s` =~ 'raspberrypi' ]]; then
  export COMP='rπ3'
  source $HOME/.zsh_config/zsh/_pi
elif [[ `hostname -s` =~ 'tux' ]]; then
  export COMP='cae'
  source $HOME/.zsh_config/zsh/_chtc
elif [ -f /.dockerenv ]; then
  export COMP='docker'
  source $HOME/.zsh_config/zsh/_docker
elif [[ `hostname -s` =~ 'ip-172-31-27-180' ]]; then
  export COM='AWS'
  source $HOME/.zsh_config/zsh/_kermit
elif [[ `hostname -s` =~ 'BrightMonolith' ]]; then 
  eval "$(pyenv init -)"
  export COMP='iMac'
  source $HOME/.zsh_config/zsh/_mbp
  export CORE_MAKE=4
  test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
else
  eval "$(pyenv init -)"
  export COMP='mbp'
  source $HOME/.zsh_config/zsh/_mbp
  export CORE_MAKE=4
  test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
fi
export PATH="/usr/local/opt/openjdk/bin:$PATH"
