#/bin/zsh
# Killer: share history between multiple shells
setopt SHARE_HISTORY
#
# # If I type cd and then cd again, only save the last one
setopt HIST_IGNORE_DUPS
#
# # Even if there are commands in between commands that are the same, still only save the last one
setopt HIST_IGNORE_ALL_DUPS

DEFAULT_USER=mouginot

if [[ `hostname -s` =~ 'BrightMonolith' ]]; then
  eval "$(pyenv init -)"
  export COMP='iMac'
  source $HOME/.zsh_config/zsh/_mbp
  export CORE_MAKE=4
  test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
else
  eval "$(pyenv init -)"
  export COMP='mbp'
  source $HOME/.zsh_config/zsh/_mbp
  export CORE_MAKE=4
  test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
fi
export PATH="/usr/local/opt/openjdk/bin:$PATH"
